### ISSUE TITLE
need clarification...

### ISSUE THREAD

**Issue by tbillion** [Jerther/psxlib#1]
why?

```
Psx Psx;
setupPins(dataPin, cmndPin, attPin, clockPin, delay)
```
!= to

```
void setupPins(byte, byte, byte, byte);			// (Data Pin #, CMND Pin #, ATT Pin #, CLK Pin #)
													
```

**Comment by Jerther** [comment]
The delay parameter was removed in https://github.com/Jerther/psxlib/commit/5c1ad60bee24bb0e93318274614a7fe3ebe828f4 but apparently I forgot to update some docs... Thanks for pointing that out. I'll fix that soon.
